"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: FingerMsgs
  IDL file: finger_msgs.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import FingerMsgs


@dataclass
@annotate.final
@annotate.autoid("sequential")
class FingerCmd(idl.IdlStruct, typename="FingerMsgs.FingerCmd"):
    tau_ff: types.array[types.float64, 3]
    q: types.array[types.float64, 3]
    dq: types.array[types.float64, 3]
    kp: types.array[types.float64, 3]
    kv: types.array[types.float64, 3]


@dataclass
@annotate.final
@annotate.autoid("sequential")
class FingerState(idl.IdlStruct, typename="FingerMsgs.FingerState"):
    q: types.array[types.float64, 3]
    dq: types.array[types.float64, 3]
    tau: types.array[types.float64, 3]


@dataclass
@annotate.final
@annotate.autoid("sequential")
class FingerImage(idl.IdlStruct, typename="FingerMsgs.FingerImage"):
    data: types.sequence[types.byte]
    timestamp: str

Array7 = types.typedef['FingerMsgs.Array7', types.array[types.float64, 7]]

@dataclass
@annotate.final
@annotate.autoid("sequential")
class FingerObjects(idl.IdlStruct, typename="FingerMsgs.FingerObjects"):
    names: types.sequence[str]
    poses: types.sequence['FingerMsgs.Array7']


